apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k7gwb4ylo-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1588e9c811.2ctv.p3.openshiftapps.com/rhtap/rhtap-qe:ec691f370a63c01009f7619fa74fed44a1c5acba@sha256:f5634bd6cbbeca9a237568ec6423d7a0f5b3434b12ce04733b68be011ec7e125
          name: container-image
